plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "H:\\Quảng khu vực làm việc\\các dự án\\landing page\\aitcv-esg-master's-program\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]